#version: '3'

services:
  app-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: app-api-1
    image: golang-vips-dev:3
    network_mode: "host"
#    ports:
#      - "8888:8888"
    volumes:
      - ../:/devServer
    environment:
      - PORT=8080